# Generated by Django 5.0 on 2023-12-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_category_options_product_is_sale_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="half_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="product",
            name="is_fifty_off",
            field=models.BooleanField(default=False),
        ),
    ]
